[package]
name = "wayland-application-switcher"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "was"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
zbus = { version = "4", default-features = false, features = ["async-io"] }
ntui = "0.1"
tokio = { version = "1", features = ["rt", "macros"] }
anyhow = "1"

